### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by preddy4690** [Eveneum/Eveneum#1]
Hello,

This is really cool to see an EventStore implementation using CosmosDB. Is there any documentation or atleast a sample usage of this library that I can look at?

**Comment by jkonecki** [comment]
Hello Preetham,

I will be working on the documentation soon (I hope to have something by
the end of the year).

In the meantime you can take a look at the unit tests.
Or just create a small project and play with it - IEventStore interface
should be pretty straightforward to use.

**Comment by jkonecki** [comment]
Thanks a lot!

I already use it in production.

I'm waiting for the documentation to be finished to bump the version number
to 1.0.

**Comment by preddy4690** [comment]
Jakub,

I'm running into an issue with writing events to a stream and wondering if you could help. If there is a better channel to reach out to you (eg, email), please let me know.

Let's say I want to add items to a ShoppingCart aggregate for the user 123. I want to create a stream per user, so the stream id for user 123 will be cart-123.

The first event I add, will have the streamId cart-123, documentId as cart-123~1, since version will be appended to the streamId to generate documentId.

Now when I try to add the second item, it's version will still be 1.0, so the generated documentId will be cart-123~1. This will throw an error saying document with the id cart-123~1 already exists.

Do I need to increase the version for every document that's being added?

Also, the version in the header is already updated by this point. Next time when I send the same request, it throws Optimistic Concurrency Exception. 

What's the suggested way to keep track of versions?

**Comment by jkonecki** [comment]
Hi,

You can reach me at jkonecki@gmail.com ot twitter @jakubkonecki.

Your code should keep track of the version of the stream it's writing to.
When you write the first event you know that the stream is in version 1.
When you read the stream, the currect version is returned to you.

You are expected to provide the 'version of the stream you are appending
to' when you write your second event.

I use an actor framework (Microsoft Orleans) with each actor representing a
single stream. Each actor will keep the current stream version locally.

Please feel free to contact me, happy to help!

Jakub
<http://www.vimeo.com/jkonecki>

**Comment by jkonecki** [comment]
Documentation is provided in a form of GitHub wiki

**Comment by eric-swann-q2** [comment]
It would be very helpful to have a very simple reference app to see how this would best be incorporated into a simple API with a couple of commands and read models.  I think if you had that you would find a lot more interest.

**Comment by Max-Eriksson** [comment]
I have the same issue. I write my first event using 

```
await eventStore.WriteToStream(newEvents.First().StreamId, payload);
```

The, whenever I get an update I try to write to the same stream using:

```
await eventStore.WriteToStream(newEvents.First().StreamId, payload, data.Stream.Value.Version);
```
In the code above the **Version** has the same value sa **Version** in the `header document`.


But this give me the error:

```
Stream '556502' already exists.
```

What am I missing?
