### ISSUE TITLE
Consider raising a different exception when reading/writing from a stream that is deleted

### ISSUE THREAD

**Issue by helloworld65** [Eveneum/Eveneum#11]
Great project, been enjoying it so far 👍 
Would you consider raising a 'StreamDeletedException' or something instead of using 'StreamNotFoundException' when attempting to read/write from a stream that has been soft-deleted? 
I think the differentiation would give more flexibility in logic that handles EventStore exceptions.

**Comment by jkonecki** [comment]
The initial idea was not to differentiate between situations when stream
doesn't exist and stream is deleted. I'm happy to change it.

Will try to get it done tomorrow.

Could you explain why you need to differentiate? How your logic would
differ in those two scenarios?

Thanks for positive feedback! 🙏

**Comment by helloworld65** [comment]
Thank you for the prompt response, I am not in a hurry so please take the time you feel you need for improvements.

I am experimenting with some sort of internal API that manages the events streams. As such I am looking for a simple way to handle any errors on the EventStore operations and return HTTP status codes that best represent the errors.

[404] - For StreamNotFoundException where the target stream id never existed
[410] - For when a stream used to exist but was deleted. The benefit of being able to determine this is it becomes another decision point for the system/user on whether to accept this error or restore the stream back to active state.

Cheers,

**Comment by jkonecki** [comment]
The changes will be soon published as version 4.3.0.

Are you on Twitter? If you want me to attribute the request to you, please let me know your handle.

**Comment by jkonecki** [comment]
https://github.com/Eveneum/Eveneum/releases/tag/4.3.0

**Comment by helloworld65** [comment]
> The changes will be soon published as version 4.3.0.
> 
> Are you on Twitter? If you want me to attribute the request to you, please let me know your handle.

@albinma168
