### ISSUE TITLE
Add support for QueryDefinition input parameter in IAdvancedEventStore

### ISSUE THREAD

**Issue by Paligora** [Eveneum/Eveneum#12]
Hello,

I've encountered a problem regarding IAdvancedEventStore.LoadEvents and IAdvancedEventStore.LoadStreamHeaders methods. The input parameter is string and it works fine, but since I have some input parameters, it would be really nice if we could use those 2 methods with QueryDefinition instead of string as input query. The QueryDefinition class allows for parameterized queries. I see that the input query is only used in Container.GetItemQueryIterator call, which has another overload with QueryDefinition as input parameter. 

This are the current overloads:

```
Task<Response> LoadEvents(string query, Func<IReadOnlyCollection<EventData>, Task> callback, CancellationToken cancellationToken = default);
Task<Response> LoadStreamHeaders(string query, Func<IReadOnlyCollection<StreamHeader>, Task> callback, CancellationToken cancellationToken = default);
```

What I am suggesting is:

```
Task<Response> LoadEvents(QueryDefinition query, Func<IReadOnlyCollection<EventData>, Task> callback, CancellationToken cancellationToken = default);
Task<Response> LoadStreamHeaders(QueryDefinition query, Func<IReadOnlyCollection<StreamHeader>, Task> callback, CancellationToken cancellationToken = default);
```

Can we have 2 more overloads or change the existing ones to use QueryDefinition?
I can provide a PR for this if required.

Goran

**Comment by jkonecki** [comment]
Hi Goran,

This is a very good idea! It would be brilliant if you could create a PR.

**Comment by jkonecki** [comment]
Thank you for a speedy submission ;-)
I'll tidy up the code, add unit tests and release the new version in the next day or so.

**Comment by jkonecki** [comment]
Goran, are you on twitter? I'll like to credit your contribution.

**Comment by Paligora** [comment]
Thank you. 

I'm not on twitter. Credit the contribution to @nomnio please.
