### ISSUE TITLE
How to Use ReplaceEvent (in EventStore.cs)

### ISSUE THREAD

**Issue by Zelcider** [Eveneum/Eveneum#15]
Hello,

I was wondering how to migrate one stream and i saw the method ReplaceEvent in the Eventstore.

My situation :

  I have an event FirstEvent.cs witch has tree properties : Id, Date, Comment.
  I would like to migrate that event to the SecondEvent.cs witch has tree properties : Id, Date , An Array of Comment.
  What do you suggest in this case ?

Sorry for any mistakes. English is not my native language.

Zelcider.

**Comment by jkonecki** [comment]
Hi Zelcider,

I would write a short program that would 
1. load all affected events using `IAdvancedStore.LoadEvents`
1. loop through them
1. convert old event to new event
1. write new event to stream using `IAdvancedStore.ReplaceEvent`

Does it help?

**Comment by Zelcider** [comment]
Hi jkonecki,

Thanks you for your quickly response.

We successfully migrate with your help.
