### ISSUE TITLE
Indexing policy guideline 

### ISSUE THREAD

**Issue by FrederickRies** [Eveneum/Eveneum#16]
Hello all Eveneum's mainteners,

We are in the process of optimizing the use of our database and were wondering if you have any suggestions on the indexing policy to be implemented in cosmosDB for Eveneum.
As of this writing, everything is indexed and it looks a bit overwhelming.
Hope you can help us in this task. Maybe you will add it to your github wiki because it is a great guideline.

Anyway, thank you very much for this superb library.

**Comment by jkonecki** [comment]
Hello @FrederickRies  and thank you very much for your kind words! 

I've added a new wiki page that hopefull answers your questions.
https://github.com/Eveneum/Eveneum/wiki/Indexing

Please let me know if the explanation is clear or if you have any more questions.
