### ISSUE TITLE
Consider if the Stored procedures should be versioned

### ISSUE THREAD

**Issue by AriKuorikoski** [Eveneum/Eveneum#17]
There are scenarios where we run 2 different Eveneum versions side by side a moment. If the stored procedures used would be versioned (e.g. have version in the name Eveneum.BulkDelete.4.6,0) each application we deploy would use the correct version.

**Comment by jkonecki** [comment]
Hi - sorry for late reply. 
New version will be introduced when there are any breaking changes. I do not expect any changes to this sproc in a forseeable future.
