### ISSUE TITLE
WriteException: Message isn't clear on what went wrong

### ISSUE THREAD

**Issue by ThomasVandenbon** [Eveneum/Eveneum#18]
I'm using Eveneum in Azure and have noticed that you can't really tell what has gone wrong when a `WriteException` occurs via Application Insights.

Example of a `WriteException`

Event time | 12/10/2020, 11:25:25 AM (Local time) 
-- | -- 
Message | Exception of type 'Eveneum.WriteException' was thrown. 
Exception type | Eveneum.WriteException 
Failed method | Eveneum.EventStore+<WriteToStream>d__25.MoveNext 
Severity level | Error 
Telemetry type | exception 
Problem Id | Eveneum.WriteException at Eveneum.EventStore+<WriteToStream>d__25.MoveNext 
Assembly | Eveneum, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null 

In contrast here is an example of an `OptimisticConcurrencyException` where the `Message` for each exception of this type clearly indicates the problem.

Event time | 12/10/2020, 11:25:27 AM (Local time) 
-- | -- 
Message | Expected stream '_Removed stream id_' to have version 190 but was 191. 
Exception type | Eveneum.OptimisticConcurrencyException 
Failed method | Eveneum.EventStore+<WriteToStream>d__25.MoveNext 
Severity level | Error 
Telemetry type | exception 
Problem Id | Eveneum.OptimisticConcurrencyException at Eveneum.EventStore+<WriteToStream>d__25.MoveNext 
Assembly | Eveneum, Version=4.6.0.0, Culture=neutral, PublicKeyToken=null

I've gone through the Application Insights logs and I can't find the `StatusCode` of the `WriteException` or a more descriptive `Message` anywhere.

Am I blind, or is something going wrong for these exceptions?

_Note: I'd like to tell you more about the circumstances in which this `WriteException` occurs, but sadly that's what I'm trying to figure out_ 😅

**Comment by jkonecki** [comment]
Hello Thomas,

Thanks for reporting this.
WriteException is thrown when we receive non-successful response from
CosmosDB.
The exception message should contain the error message returned by Cosmos
SDK. Same applies for Status Code.

Can you see StreamId or RequestCharge properties in AppInsights?

Which version of Eveneum are you using?

Regarding the underlying issue: are your requests to Cosmos being
throttled? If so, you might want to increase number of retries and timeout
period in CosmosClient used by Eveneum. Or increase provisioned RU/s.

Jakub

**Comment by ThomasVandenbon** [comment]
Thank you Jakub for the fast response.

However, I've had a realization that this might not be related to Eveneum directly.
The project I'm working on is using [Hellang ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails) and I'm starting to wonder if it might be eating some of the exception information.
I'll investigage this further and get back to you.

As for your questions:

> WriteException is thrown when we receive non-successful response from
CosmosDB.
The exception message should contain the error message returned by Cosmos
SDK. Same applies for Status Code.
> Can you see StreamId or RequestCharge properties in AppInsights?

I had gone through the source code and had seen these properties.
But I cannot find any of them in Application Insights.

> Which version of Eveneum are you using?

I'm using 4.6.0

> Regarding the underlying issue: are your requests to Cosmos being
throttled? If so, you might want to increase number of retries and timeout
period in CosmosClient used by Eveneum. Or increase provisioned RU/s.

I've checked the throughput and no throttling is taking place.

**Comment by jkonecki** [comment]
Thanks for coming back to me.

I'll keep the issue open for now and do some testing on my end. Please post
any updates you might have.

**Comment by ThomasVandenbon** [comment]
I've disabled [Hellang ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails), but I'm not seeing any additional exception info.

As an additional test, I've replaced the `WriteToStream` call by `throw new FileNotFoundException(message, fileName);` as it is one of the few non-custom exceptions I know that has a property (`FileName`). However, this property doesn't seem to show up in Application Insights either.

Which leads me to the conclusion:
- Either there is something missing in my Application Insights configuration
- Or the default behaviour of Application Insights is not to track exception information beyond the message, stack trace and the context.


Jakub, are you using Application Insights with Eveneum?
If so, are you seeing the details for these exceptions?
For example, in the Application Insights Logs, are they part of the `customDimensions` or `details` perhaps?

**Comment by ThomasVandenbon** [comment]
After reading https://github.com/microsoft/ApplicationInsights-dotnet/issues/1932, I think it's safe to assume that Application Insights doesn't track exception information beyond the message, stack trace and context without custom configuration.
This leads me to believe that they expect the message to contain enough information to be able to understand the problem.

If you'll allow me to make a suggestion: maybe the constructor for `WriteException` could be changed so the message holds more information (similar to the other custom exceptions)?
Something like: `$"Unsuccesful response (StatusCode '{response.StatusCode}') when writing to Cosmos: {response.ErrorMessage}"`.

_Note: The exception could still hold the inner exception and the additional properties so that custom configuration could still allow each property to be logged as an individual field._

**Comment by jkonecki** [comment]
Thank you very much for your research.

I'll make the change over the weekend and publish the new version.

Will this work for you?

**Comment by jkonecki** [comment]
I've published a new package `Eveneum.ApplicationInsights`. It contains `EveneumTelemetryInitilizer` which, when added to your configuration, will generate properties for all Eveneum exceptions.

`TelemetryConfiguration.Active.TelemetryInitializers.Add(new EveneumTelemetryInitializer());`

I'll create a wiki entry later on and post a link here - but you can have a go now.

**Comment by jkonecki** [comment]
Wiki has been updated: https://github.com/Eveneum/Eveneum/wiki/ApplicationInsights-integration

Please reopen this issue if you need more assistance.

**Comment by ThomasVandenbon** [comment]
Thank you for the quick fix!

I've just tested it and I can confirm that after adding the `Eveneum.ApplicationInsights`-package, I can now see the custom properties in ApplicationInsights 👍 

Regarding the [Wiki page](https://github.com/Eveneum/Eveneum/wiki/ApplicationInsights-integration#installation): The installation instructions you've listed are for .NET Framework, in addition to these, you might also want to add the approach for .NET Core (which is what I've used):

```cs
public void ConfigureServices(IServiceCollection services)
{
    // ...
    services.AddSingleton<ITelemetryInitializer, EveneumTelemetryInitializer>();
}
```
_(See https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#addmodify-properties-itelemetryinitializer)_

_Personally, (in addition to this package) I would have still considered changing the `WriteException` message to at least include the `StatusCode`, since the current message doesn't really tell you anything (as opposed to the other custom exceptions which are very descriptive). But I guess that's a matter of taste 😉_

**Comment by ThomasVandenbon** [comment]
@jkonecki 
For your information, while I did manage to get it working for an Web.API project.
I haven't managed to get the application insights for Azure Functions to pick-up this Initializer.
But I think this problem is more related to the integration between Application Insights and Azure Functions than your implementation.

**Comment by jkonecki** [comment]
Hi, I haven't used AppInsights inside Azure Functions myself so I won't be
able to help you here. There's nothing extraordinary going on in the
initializer, so I would assume it's related to the configuration. Are you
sure the DLL is actually deployed (just a thought)?

**Comment by jkonecki** [comment]
> _Personally, (in addition to this package) I would have still considered changing the `WriteException` message to at least include the `StatusCode`, since the current message doesn't really tell you anything (as opposed to the other custom exceptions which are very descriptive). But I guess that's a matter of taste 😉_

4.7.1 - with best Xmas wishes ;-)

**Comment by jkonecki** [comment]
@ThomasVandenbon you might want to upgrade to 4.8.0 in order to use the new telemetry initializer for `CosmosException` - https://github.com/Eveneum/Eveneum/wiki/ApplicationInsights-integration#cosmos-telemetry-initializer

**Comment by ThomasVandenbon** [comment]
Sorry for the delay Jakub.
Today I've upgraded to `4.8.0` and I've included the second telemetry initializer along with the first.

I've had a look through Application Insights and I can't see any `CosmosException` in our logging in the past month.
Out of curiosity: Are you hoping to target a specific scenario for these CosmosExceptions or is it more of a precaution?

Happy hollidays to you too! 🎄

**Comment by jkonecki** [comment]
Hi, this is just to add extra properties for any logs for CosmosException.
No particular reason, just wanted to piggy back on the work for the other
initializer.

In some of my projects I'm using Cosmos SDK for persisting projections, and
this initializer may be handy there as well.
