### ISSUE TITLE
LoadStreamHeaders does not load soft deleted headers

### ISSUE THREAD

**Issue by AriKuorikoski** [Eveneum/Eveneum#19]
I am planning to use LoadStreamHeaders method for loading streams having changes since a certain time. The load is done scheduled: For example I first load headers having changes since 1.1.2021. and then load streams that are on different version to my read repository.

When an aggregate is set to deleted state, I also soft delete it's stream. With this procedure I was expecting to be able to figure from the stream header, when the stream is having new events, or when the stream is deleted and reflect that to my read repo but it seems the method doesn't return soft deleted headers:

`await callback(page.Where(x => x.DocumentType == DocumentType.Header).Where(x => !x.Deleted).Select(x => new StreamHeader(x.StreamId, x.Version, this.Serializer.DeserializeObject(x.MetadataType, x.Metadata))).ToList());`

I would appreciate if this could be modified to suit my needs. 

- Ari

**Comment by jkonecki** [comment]
Hello Ari, that is a reasonable request. I'll try to implement it and push
the new version out in a few hours.

**Comment by jkonecki** [comment]
Hi Ari - NuGet package has been pushed.

https://github.com/Eveneum/Eveneum/releases/tag/5.0.0

You don't need to make any changes in your code to load soft-deleted header.
However, you might want to exclude soft-deleted event if you're using `LoadEvents`. 

Please see release notes above for more details.

**Comment by jkonecki** [comment]
@AriKuorikoski , you may be interested in upgrading to version 5.1.0 (https://github.com/Eveneum/Eveneum/releases/tag/5.1.0) as it has some performance improvements that you will benefit from in `LoadStreamHeaders`

**Comment by AriKuorikoski** [comment]
@jkonecki, I just updated to latest version and realized that the StreamHeader doesn't expose if the stream is deleted or active. Could you consider making the isDeleted property visible on the class? Could be also usable on EventData class.

**Comment by jkonecki** [comment]
Yes, of course, I totally missed that!

**Comment by jkonecki** [comment]
NuGet package with version 5.2.0 has been published.
