### ISSUE TITLE
Expose the events time stamp 

### ISSUE THREAD

**Issue by AriKuorikoski** [Eveneum/Eveneum#20]
We're building a report on which we need the time when certain event was stored to our event store. Unfortunately those events until now, didn't store the date time as value in the event data and we can't use the event for reporting purposes.

Is there any chance that  EveneumDocument could expose the _ts property from Cosmos record as well as on the Event Data?

Thanks  a lot in advance!

**Comment by jkonecki** [comment]
Hi!

Yes, I can expose _ts.

The best place to store timestamps explicitly is in the metadata.

Jakub

**Comment by AriKuorikoski** [comment]
Thank you a lot!

Using the metadata is exactly where we added the timestamp for the new version of events. Every time event is created, we add date time property on the metadata with a few other common properties that really don't have anything to do with the actual event.

**Comment by jkonecki** [comment]
Version 5.3.0 has been released.
