### ISSUE TITLE
github wiki quick start is not readable

### ISSUE THREAD

**Issue by anyei** [Eveneum/Eveneum#21]
The quick start section under the wiki is not readable. It seems like there's a typo making it break.

**Comment by jkonecki** [comment]
Coud you please provide a screenshot of the page and your browser details? 
I cannot see any problems in desktop Firefox and Edge, nor in mobile Firefox

**Comment by anyei** [comment]
Thanks again!

Closing it with the same comment as https://github.com/Eveneum/Eveneum/issues/22#issuecomment-783792203
