### ISSUE TITLE
github wiki overview is not readable

### ISSUE THREAD

**Issue by anyei** [Eveneum/Eveneum#22]
The overview section under the wiki is not readable or not well formatted. Html is mixing up with the content.

**Comment by jkonecki** [comment]
Coud you please provide a screenshot of the page and your browser details? 
I cannot see any problems in desktop Firefox and Edge, nor in mobile Firefox

**Comment by anyei** [comment]
Thanks for taking time and replying back. I have failed taking a screenshot unfortunately.. and it seems the wiki is showing all the pages ok now. I was thinking it could be something related to github itself it was weird. Nevertheless i'll be on the lookout since I'm working with your library on an active project. I will close these (i have two issues reported with the same thing basically) and in any case it happens again i'll screenshot it for you.

Thanks!

**Comment by jkonecki** [comment]
Thank you, Angel - it does seem to me as a github issue as well. Wiki is stored as markdown and it's github that generates HTML.
Have a lovely day!
