### ISSUE TITLE
Split into several smaller repos?

### ISSUE THREAD

**Issue by norvegec** [Eveneum/Eveneum#24]
I'm testing this out with scenario like the following: Cosmos + Event feed + Azure Functions.
It would be so cool to start with essential features (core) and only if required opt-in to add snapshot or bulk delete capabilities by plugging in feature nuget packages.

**Comment by jkonecki** [comment]
Thank you for a suggestion.
I believe that the maintenance overhead for managing separate repo / build / release and nuget package just for one or two methods is too great.
Also, snapshots are a core feature that the event store need to be aware of. You don't have to use them if there's no need for them.
