### ISSUE TITLE
Batch write is not atomic?

### ISSUE THREAD

**Issue by norvegec** [Eveneum/Eveneum#26]
events are split into batches, each batch in a loop is wrapped in transaction and persisted:
https://github.com/Eveneum/Eveneum/blob/e353061e1ec59164df38dcf44809784e88ca3872/Eveneum/EventStore.cs#L175

But ~if~ when something goes wrong between batch writes, i.e. host dies, network error, etc. then system would have inconsistent state (_some_ events persisted, some not).

**Comment by norvegec** [comment]
I suppose this number of simultaneous events to persist could only happened during some kind of maintenance (migration)?
So it might not be an issue, cause the system is being monitored by dev/devops/sre/whoever-it-is.
Also it could be a clue to start making snapshots?

Could you please clarify the case?

**Comment by jkonecki** [comment]
A batch cannot be fully atomic with a large number of events, as this is a limitation of CosmosDB.
It is probably an edge case scenario for an application to append over 99 events in a single write. 
What is more, the SDK implements retries for transient errors, so the chance of expiriencing a 'partial commit' is in my opinion minimal.

The application can handle exceptions from Eveneum methods and retry.

I was considering adding retries in EventStore, but my guess is that if the SDK retries didn't work than keeping retrying will probably cause more harm than good.
