### ISSUE TITLE
Moving from EventStore to Eveneum -- are there any guides or sample projects?

### ISSUE THREAD

**Issue by lawrenceong001** [Eveneum/Eveneum#27]
Hello,

as the title implies, I am in the process of exploring the replacement of EventStore with Eveneum since we are now using CosmosDb for our project. I was wondering if there are any guides we can use to see how we can achieve this. Sample projects would also be very helpful since they can give us an indication of its features. 

tks.

**Comment by jkonecki** [comment]
Hi!

A sample project is located here: [https://github.com/Eveneum/Sample](https://github.com/Eveneum/Sample)

It doesn't show all the features though. You might want to go throught the [wiki](https://github.com/Eveneum/Eveneum/wiki) and unit tests.

When it comes to data migration, I would suggest creating a console app that will read all your streams from EventStore and push them the CosmosDB. For best performance, process multiple streams in parallel and create full streams with all events in Eveneum: appending individual events to each stream will result to multiple roundtrips to CosmosDB, higher latency and higher RU/s usage. Eveneum will bulk import multiple events in one request, so pass all the events to `WriteToStream` in one go.

Let me know if you have more questions.
