### ISSUE TITLE
In Place Copy-Replace

### ISSUE THREAD

**Issue by ThomasVandenbon** [Eveneum/Eveneum#28]
Hi,

We've been using Eveneum as part of our event-sourced application for a while now and so far it has served us well 👍 
Thank you @jkonecki !

Over-time we've started applying upcasters to convert old event-schemas to new ones (in-memory, at runtime), but we've reached the point where we'd like to apply a migration to our store to remove some of these old version and reduce our upcasting code.

To perform this migration we were drawn to  an **“in place copy-replace”** strategy as described in [Versioning in an Event Sourced System](https://leanpub.com/esversioning/read) by Gregory Young.
The way we'd like to tackle this is as follows:
- The events are upcasted to their latest version using our existing upcasting code
- The upcasted version of these events are added to the same stream (hence “in place”, since it uses the same stream)
- Additionally, we'd add 2 ‘audit events’, one before and one after the upcasted events respectively (e.g. `CopyReplaceStarted` and `CopyReplaceFinished`). 
  - The purpose of these is to provide insight in what occurred within the stream for anyone who might check the stream in the future.

Our event consumers are running asynchronously and are heavily reliant on the ‘Cosmos DB Change Feed’.
This means that:
- We prefer not to update any "old" event document (as this would trigger the changes to appear in the change feed). So we'd rather not flag them as being ‘soft deleted’.
- In the future we might remove the "old" event documents completely, but to avoid problems with asynchronous processing we don't want to delete them right away.
 
To be able to accomplish our flavor of **in place copy-replace**, we've found that we'd need the following features: 
- [x] Adding MetaData to the StreamHeader containing the new starting point of the stream
  - This is already possible with Eveneum 👍
- [x] The ability to read the metadata of a stream before reading the actual stream. This would allow us to determine where the stream starts, to then only start reading from that point (skipping the clutter from the past). 
  - Reading the header of a specific stream is currently problematic. There seems to only be a way to read multiple headers using `LoadStreamHeaders`. This problem would probably be fixed if `ReadHeader` on `EventStore` was made `public` (instead of `private`) 
- [x] Finally, we'd need 2 ways of reading a stream from a specific version. One that ignores all Snapshots, so that we could perform a 2nd copy-and-replace starting from a position in the stream. And a second that takes Snapshots into account and so reads as little events as possible (stopping at the first snapshot), to keep our aggregate loading efficient. 
  - This is currently not possible because `ReadStreamFromVersion` ignores the snapshots, and `ReadStream` doesn’t have an option to read from a certain point. To accomplish this, we'd need a combination of these 2 methods. 
     As an example, this could be an optional `RequestOptions` on `ReadStream` (similar to the Cosmos API), where the `RequestOptions` exposes the following options:
      - `bool IgnoreSnapshots` (`false` for rehydration of aggregates, `true` when reading the entire stream to perform a migration)
      - `ulong? Version` (to avoid loading events from before the copy-replace migration)

We're willing to contribute to Eveneum in the form of a PR to add these missing features.
But before we start working on this, we wanted to first ask:
- What is your opinion about our approach?
- Are you open to PR's that would add the features we're missing?
  - Is there something we should keep in mind?

Thank you in advance!

**Comment by jkonecki** [comment]
Hi Thomas,

What do you think about the following changes:

1. `ReadHeader` method is made `public` and added to `IReadStream` interface
2. A new `ReadStream(ReadStreamOptions options)` method is added to `IReadStream` interface. The options parameters has properties:
   - ulong? FromVersion = null
   - ulong? AsOfVersion = null
   - bool IgnoreSnapshots = false
3. Exisitng four `ReadStream` methods are marked as `Obsolete` and their implementation calls new `ReadStream(ReadStreamOptions)` method with appropriate parameters set.

Does the above satisfy your requirements? If so, you can proceed with implementation.

Please let me know if you have any questions or if you need any help with implementation.

**Comment by ThomasVandenbon** [comment]
Thank you for the quick replies and guidance regarding the implementation!
We haven't started on the implementation yet, but this sounds like it would work.

One more suggestion before we start:
We've noticed some confusion within our team in the naming of `FromVersion` and `AsOfVersion`.
Some people incorrectly thought that `AsOfVersion` meant that the stream would be read starting from that version (the behaviour of `FromVersion`), they were then confused when they discovered the existance of `FromVersion`.
A suggestion that came up was to rename `AsOfVersion` to `UntilVersion` or `UpToVersion` instead.

This won't block us from getting started and is only an idea (feel free to decline the suggestion), but it could be some food for thought 😉

**Comment by jkonecki** [comment]
Could you please rename `AsOfVersion` property on the options class to `ToVersion`? I think it may be a more clearer alternative, especially when compared to `FromVersion`.

**Comment by ThomasVandenbon** [comment]
`ToVersion` is a good suggestion, we'll include this in our PR 👍

I've had a quick look at how we might tackle the implementation and I noticed 2 things:
1. `ReadStream` (public) and `ReadStreamAsOfVersion` call `ReadStream` (private) with a `maxItemCount` of `100`, while `ReadStreamFromVersion` and `ReadStreamIgnoringSnapshots` use `QueryMaxItemCount` (which comes from the `EventStoreOptions`).
   1. Shouldn't all of these use `QueryMaxItemCount`?
   2. Should the `ReadStreamOptions` that were mentionned above include this `QueryMaxItemCount`?
2. The new `ReadStreamOptions` will mean that there will be 8 different possible query-strings. For now, this can be a big chain of `if`-conditions, but it might be worthwile to consider using a [specification pattern](https://en.wikipedia.org/wiki/Specification_pattern) to make the code more readable and maintainable in the future.
The queries I'm thinking of:
   1. No options: `SELECT * FROM x ORDER BY x.SortOrder DESC`
   2. Ignore snapshots: `SELECT * FROM x WHERE x.DocumentType <> 'Snapshot' ORDER BY x.SortOrder DESC`
   3. From version: `SELECT * FROM x WHERE x.Version >= {version} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`
   4. From version and ignore snapshots: `SELECT * FROM x WHERE x.DocumentType <> 'Snapshot' AND x.Version >= {version} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`
   5. To version: `SELECT * FROM x WHERE x.Version <= {version} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`
   6. To version and ignore snapshots: `SELECT * FROM x WHERE x.DocumentType <> 'Snapshot' AND x.Version <= {version} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`
   7. From/To version: `SELECT * FROM x WHERE x.Version >= {fromVersion} AND x.Version <= {toVersion} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`
   8. From/To version and ignore snapshots: `SELECT * FROM x WHERE x.DocumentType <> 'Snapshot' AND x.Version >= {fromVersion} AND x.Version <= {toVersion} OR x.DocumentType = 'Header' ORDER BY x.SortOrder DESC`

We're looking forward to hearing what's your opinion about this.

**Comment by ThomasVandenbon** [comment]
@jkonecki you wrote:
> * A new `ReadStream(ReadStreamOptions options)` method is added to `IReadStream` interface. The options parameters has properties:
>   
>   * ulong? FromVersion = null
>   * ulong? AsOfVersion = null
>   * bool IgnoreSnapshots = false
> * Exisitng four `ReadStream` methods are marked as `Obsolete` and their implementation calls new `ReadStream(ReadStreamOptions)` method with appropriate parameters set.

I believe you meant to also include the `streamId` as a parameter in the new method: `ReadStream(string streamId, ReadStreamOptions options = null, CancellationToken cancellationToken = default)`.

However, if we mark the existing `ReadStream` method as `Obsolete` then this will mean that calling `ReadStream` with only a `streamId` will result in an ambiguous reference. 
I would therefor suggest to remove the original `Task<StreamResponse> ReadStream(string streamId, CancellationToken cancellationToken = default);` method entirely and mention that it has been replaced by `Task<StreamResponse> ReadStream(string streamId, ReadStreamOptions options = default, CancellationToken cancellationToken = default);`.

An alternative would be to include `streamId` as an option on `ReadStreamOptions`, but this feels wrong to me.

**Comment by jkonecki** [comment]
Yes, you are correct. I was too terse in my description, sorry.

Wee need only `ReadStream(string streamId, ReadStreamOptions options = null, CancellationToken cancellationToken = default)` and it will replace existing methods. 

I will bump a major version number.

**Comment by jkonecki** [comment]
> The new ReadStreamOptions will mean that there will be 8 different possible query-strings. For now, this can be a big chain of if-conditions

Please go ahead with `if-else` chain for the time being. I don't think we need 8 different `ifs` as we can construct the query dynamically. Don't worry too much about it, I can refactor the code in PR.

**Comment by jkonecki** [comment]
Hello Thomas - NuGet package with version 6.0.0 has been published. It may take a few moments for NuGet.org to index it.

Please close this issue if all is working fine or let me know if any other changes are needed.

Many thanks for your time and contribution!

**Comment by ThomasVandenbon** [comment]
@jkonecki Thank you for your time as well!

I've found one thing that feels off.
When we made `ReadHeader` public, we also exposed `EveneumDocument`, which was probably an error.
The reason being that fields like `MetaData` are of type `JToken`, while on the similar `Stream` they're of type `object`.

We probably should have created a new `ReadHeader` method that uses the existing `ReadHeader`, but converts the response to a DTO, something like a `HeaderResponse` where these fields have already been serialized.

Similar to this code from `ReadStream`:
```csharp
var events = documents.Where(x => x.DocumentType == DocumentType.Event).Select(this.Serializer.DeserializeEvent).Reverse().ToArray();
var snapshot = documents.Where(x => x.DocumentType == DocumentType.Snapshot).Select(this.Serializer.DeserializeSnapshot).Cast<Snapshot?>().FirstOrDefault();
var metadata = this.Serializer.DeserializeObject(headerDocument.MetadataType, headerDocument.Metadata);

return new StreamResponse(new Stream(streamId, headerDocument.Version, metadata, events, snapshot), false, requestCharge);
```
_See https://github.com/Eveneum/Eveneum/blob/master/Eveneum/EventStore.cs#L129_

**Comment by jkonecki** [comment]
I was actually thinking about the same thing.

Can you please let me know what data from header EveneumDocument do you
need?
Just MetaData and Version?

**Comment by ThomasVandenbon** [comment]
From the header document we currently only need `MetaData`.

But perhaps https://github.com/Eveneum/Eveneum/blob/master/Eveneum/StreamHeader.cs should be reused (as it currently is)?
Since it's already being exposed in `LoadStreamHeaders` on `IAdvancedEventStore`.

```csharp
public struct StreamHeader
{
    public string StreamId;
    public ulong Version;
    public object Metadata;
    public bool Deleted;

    internal StreamHeader(string streamId, ulong version, object metadata, bool deleted = false)
    {
        this.StreamId = streamId;
        this.Version = version;
        this.Metadata = metadata;
        this.Deleted = deleted;
    }
}
```

**Comment by jkonecki** [comment]
Just pushed version 6.1.1 to NuGet.org.

**Comment by ThomasVandenbon** [comment]
@jkonecki I believe something went wrong in the creation of the NUGET package.

| Version 5.3.0 | Version 6.1.1 |
| -------------- | -------------- |
| ![image](https://user-images.githubusercontent.com/20145524/145397139-d2e3b11f-0e13-4429-a660-b58ae78efb0f.png) | ![image](https://user-images.githubusercontent.com/20145524/145397218-7de324b0-a3b2-4808-89f3-58eb2d77a24e.png) |

This results in the `Eveneum` namespace nog being found in the consuming project.

**Comment by jkonecki** [comment]
Pushed a fix (6.1.2). I'm very sorry about it.

**Comment by jkonecki** [comment]
Pushed another fix - 6.1.3.
Should be available on NuGet in 15 mins or so

**Comment by ThomasVandenbon** [comment]
@jkonecki 6.1.3 hasn't appeared on NUGET yet after 17 hours. 
Could something have gone wrong?

**Comment by jkonecki** [comment]
Should be visible on NuGet.org now!

**Comment by ThomasVandenbon** [comment]
@jkonecki sorry for the delay once again.

We've managed to test the new functionality and everything is working well 👍
As far as I'm concerned this issue can be closed.

There is one more tiny improvement that could be made:
In `ReadStream` of `EventStore` a [`maxItemCount` variable is set](https://github.com/Eveneum/Eveneum/blob/master/Eveneum/EventStore.cs#L60).
This variable could be used to test the validity of the `FromVersion`-`ToVersion` range.

For example, if I provide a range from `500` to `5000`, but then set a max item count to `1000` then a result of `500` to `1500` might be unexpected.

What do you think?

**Comment by ThomasVandenbon** [comment]
Nevermind, as my colleague correctly pointed out, `maxItemCount` refers to the maximum number of items per Cosmos query, not the maximum number of results. Doh! 🤦‍♂️

Closed! 🎉

**Comment by ThomasVandenbon** [comment]
@jkonecki sure, I'm not active at all though, here you go: https://twitter.com/ThomasVandenbon.
