### ISSUE TITLE
Target netstandard 2.0 and migrate to Microsoft.Azure.Cosmos

### ISSUE THREAD

**Issue by anarsen** [Eveneum/Eveneum#3]
Trim `csproj`s by adopting the SDK-style approach and target `netstandard2.0` at the same time.

- [ ] Migrate `csproj`s to SDK style approach
- [ ] Migrate from `Microsoft.Azure.DocumentDB` to `Microsoft.Azure.Cosmos` for `netstandard2.0` support

**Comment by anarsen** [comment]
Submitting this because I could be interested in adopting this, but I require it to be compatible with `netcoreapp2.2`.

There's a good chance I'll submit a PR for this soon-ish.

**Comment by anarsen** [comment]
@jkonecki I didn't think of this until now, but we have to deprecate targeting `net452` in order to target `netstandard2.0`. There's no common denominator in the Cosmos DB SDKs unfortunately.

What's your opinion on this? Being this is a rather new library, ditching the `net452` shouldn't cause too much panic imho.

**Comment by jkonecki** [comment]
Yes, migration is planned and I hope I'll get it done within a couple of
weeks.

**Comment by anarsen** [comment]
Let me know if you need a hand.

**Comment by jkonecki** [comment]
If you would like to create a PR, I will be more than happy.

**Comment by jkonecki** [comment]
I'm almost done with the upgrade - just doing some final testing. I plan to publish a new nuget package today

**Comment by jkonecki** [comment]
The changes are pushed to `master`, tagged `2.0.0`. I have problems with generating nuget package as my Azure Pipelines account is missing VS2019 hosted agent pool. 
Reported the issue to MS.

**Comment by jkonecki** [comment]
NuGet package has been published: https://www.nuget.org/packages/Eveneum/2.0.0

**Comment by anarsen** [comment]
Awesome! I'll give it a spin this weekend.
