### ISSUE TITLE
Read events in reversed order

### ISSUE THREAD

**Issue by gzp-crey** [Eveneum/Eveneum#31]
EventStoreDB has a great feature to read events in reveresed order. I know it is not pure eventsourcing but it is a great feature display the last few (paged) event for some longer stream.
How alien would it be to add an optional reversed parameter to the stream read option and order the events in ASC order ?

**Comment by bartelink** [comment]
+1 - definitely really useful - in Equinox the dominant access strategy is to search backwards until you git an 'origin' event, which can be any event that gets us to a known state e.g. CartCleared, StateCompacted - which also generalizes as a selective snapshot processing mechanism)
Though you definitely want/need it to be indexed appropriately

**Comment by jkonecki** [comment]
I can definitely work on it - should be very simple to implement as Eveneum
is already "reading backwards" to find the latest snapshot.

**Comment by jkonecki** [comment]
To be honest, the above can already be achieved by using 
`IAdvancedEventStore.LoadEvents(string query, Func<IReadOnlyCollection<EventData>, Task> callback, CancellationToken cancellationToken = default);`

The query can contain `order by` clause to acheive the desired effect:

`SELECT * from c WHERE c.StreamId='my-stream-id' AND c.DocumentType = "Event" ORDER BY c.SortOrder DESC`

Cancellation token can be used to stop processing.

Each callback will return a page of data with the size up to `QueryMaxItemCount`. Be default Eveneum loads up to 1000 documents in each page to minimize latency. If you know upfront that the desired event will be much closer to the end of the stream, you can set `QueryMaxItemCount` to lower value.

For short streams, that are loaded in one query by `IEventStore.ReadStream` you can just reverse the array of events returned or iterate it in the reverse order. Eveneum doesn't query CosmosDB one event at the time (that would hugely increase latency) - so for streams of up to 1000 events it shouldn't make any difference in what order the events are queried: in both cases a single query that loads all documents will be issued.

Please let me know if the above helps you or if you need more info.

@gzp-crey @bartelink

**Comment by jkonecki** [comment]
That's correct - the order between events from different streams shouldn't
matter.

Other option is to include a timestamp in event metadata and order all
events by it.

You can also take a look at `LoadAllEvents` method.
