### ISSUE TITLE
Dependency versions (Newtonsoft.Json 13.0.1) 

### ISSUE THREAD

**Issue by NickKimpe** [Eveneum/Eveneum#32]
Hi,

We are upgrading the Nuget packages in our solution. One of them is `Newtonsoft.Json`, we would like to use the latest stable (which is 13.0.1 at the moment). But the Nuget package manager detected this dependency constraint:
![image](https://user-images.githubusercontent.com/3765666/168032157-620dc2e7-e25b-4f28-af74-55281cbd4b0a.png)

Is it possible to ship a new version with upgraded dependencies please?

Thanks in advance!
Nick

PS: We were able to implement our preferred data migration approach thanks to these changes: [link](https://github.com/Eveneum/Eveneum/issues/28). Still using Eveneum, still loving it! Thank you @jkonecki !

**Comment by jkonecki** [comment]
Thank you very much for your kind words. 😊

I'll work on the new version today. Should be released tomorrow at
the latest.

**Comment by jkonecki** [comment]
I've released version 6.2.0 with upgraded Json.Net package. Please re-open this issue if the problem persist.

https://www.nuget.org/packages/Eveneum/6.2.0
