### ISSUE TITLE
When a stream is set as deleted, let host set the TTL on the stream

### ISSUE THREAD

**Issue by AriKuorikoski** [Eveneum/Eveneum#33]
We have a policy where we clean up obsolete event streams, to save our hosting costs. We want to keep the stream available for 6 months after the delete event on the stream has been applied. 

When setting a stream deleted, could Eveneum introduce 3rd mode besides soft delete and hard delete? A mode where all the events in given stream would be set a TTL value declared by the host app, in our case 6 months from the time delete has been applied? This would let Cosmos handle the removal of the streams in the background without us having a process to lookup and delete obsolete streams. Also the clean up would use the left-over read-units, when there are units available, would save on hosting costs as well.

**Comment by jkonecki** [comment]
Resolved by #35
