### ISSUE TITLE
Snapshot size issues

### ISSUE THREAD

**Issue by ThomasVandenbon** [Eveneum/Eveneum#36]
Hi

We've been using Eveneum as part of our event-sourced application for a few years now and so far it is serving us very well 👍
We would like to express our gratitude to @jkonecki once again, thank you !

## The issue with Snapshot sizes

During the past years, there has been a few issues, but there is one that keeps coming back regularly: the document size of Snapshots.
To be clear, this issue doesn't originate from Eveneum, but rather from Cosmos.
Cosmos has a document size limit of 2 MB (see https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits).

Generally, our snapshots are intended to be quite small, but occasionally a client will do something absurd and end up suddenly having a Snapshot which is larger than 2 MB. Often these clients can be convinced to change the way they work, but occasionally they have a valid (unforeseen) reason for their abnormal Snapshot size.

Whenever we encountered this issue in the past years, we've been changing our aggregates, streams or events to accommodate this limit. Sadly this often results in splitting a Stream that should not be split.
What makes it worse is that we might have thousands of streams with very small snapshots and 1 that hits the limit. Meaning 1 absurd stream, makes our whole domain worse.

## Idea: Store large Snapshots as BLOBs

Since this problem is very rare (in terms of number of streams), but is so disruptive, we've been thinking of a way to allow these large Snapshots as a special case. Of course, we cannot exceed the limit of Cosmos' document sizes, but we can store them in a different storage that does allow larger documents!

### Step-by-step
- When saving a Snapshot (before serialization) we'll check the size of the JSON that will be serialized.
  - If the size is smaller than X% of the document size limit (2 MB)
    - We persist it as we normally would.
  - If the size is larger
    - We will store the JSON as a BLOB in an [Azure Storage Account](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview).
    - We then take the URI of the BLOB and store it (using Eveneum) in a Snapshot document that only contains this BLOB URI. This will be a very small document, which is useless without the linked BLOB.
- When querying a Stream
  - If we don't find a BLOB-snapshot-document
    - Then we continue as normal.
  - If we do find a BLOB-snapshot-document
    - We will replace the BLOB-Snapshot-document (read via Eveneum) with the actual Snapshot that was stored in BLOB storage.
    - _Note: if the BLOB would be unavailable, we could continue reading the stream to the next snapshot._

### ➕Positives
- Our domain is no longer impacted by these infrequent large Snapshots and can stay the way it should be

### ➖Negatives
- When persisting a Snapshot
  - We take a performance hit for checking the size of the Snapshot before persisting it
  - When dealing with a Snapshot that is deemed too large, we take a performance hit for storing it as a BLOB
- When querying a Snapshot that was deemed too large, we take a performance hit for loading it from the BLOB storage

## What does this have to do with Eveneum?

Nothing! The idea we described above can be fully implemented without a single change to Eveneum.

But...
1. We believe that this idea might be of value to other people using Eveneum.
2. We believe that one of the negatives, namely the performance hit for checking the size of the Snapshot before persiting it, could be reduced by changes to Eveneum. If we implement it as described above, then the Snapshot will be serialized twice (once in our code to check the size and [once in Eveneum](https://github.com/Eveneum/Eveneum/blob/master/Eveneum/EventStore.cs#L266) in order to persist it).

We were therefor wondering if there wouldn't be a way partially or fully include this idea into Eveneum?
The inclusion could go anywhere from:
- From (fully): Passing Storage Account credentials to Eveneum
- To (partially): Providing a fallback mechanism for the Snapshot persistance.

Aside from this, we were also just curious what you (@jkonecki) thought about this approach? Perhaps we're missing something? :)

Thank you in advance!

**Comment by jkonecki** [comment]
Thank you very much for your kind words 😊

Your idea is very interesting and it makes sense to me. I've been thinking
myself about introducing Snapshot Persistence providers that would
serialize snapshots in whatever medium you want. Eg. maybe you want to
persist snapshots into relational database for some aggregations or
indexing...

If the provider handled snapshot persistence, then Eveneum would store in
its own snapshot in CosmosDB only the info about which provider was used,
so during deserialisation this provider can be called to get the snapshot.
Blob Storage provider seems like a very common use case, and could be
included in the box.

There's only the question about error handling - should the stream write be
rejected when snapshot failed to persist? On one hand snapshots are
optional, and only an internal performance improvement. But on the other we
are currently persisting snapshot documents in the same transaction as
events.

I'm very happy to work on this. Do you have any code written - even spike -
you could share?

**Comment by ThomasVandenbon** [comment]
We're pleased to see your enthusiasm 😁

__Snapshot Persistence__
This sounds great and would most likely fit very well.
The only way it differs from our idea, is that we were planning to keep most Snapshots still in Cosmos and only persist the "annoying" ones elsewhere.
But I'm sure we could make this work for us.

__Error handling__
I might be wrong, but I thought that there was currently no way to persist both events and a snapshot in the same transaction via Eveneum. I thought that Snapshots were always persisted on their own.
If this assumption is correct, then throwing an exception seems like the most logical option. It's then up to the consumer to decide how to handle the exception.

Or is this a feature you'd like to ensure to remain possible in the future?

__Code/spike__
We haven't started on this yet. We were curious to hear your opinion first.

Is there anything I can help with to turn the idea into reality?

**Comment by jkonecki** [comment]
Hi @ThomasVandenbon - I'm nearly done with the changes. There are some final loose ends I need to sort out - like deleting custom snapshots when the stream is deleted.

I've added unit test for the new functionality, but I'm a bit hesitant with official release before you review and check the changes yourself. 

How would you like to proceed? Would you prefer to check out the branch and play with it, or use a pre-release NuGet package?

I plan to finish all the code changes tomorrow and start working on the documentation.

**Comment by ThomasVandenbon** [comment]
I had a quick glance through the code.
Overall the change looks good 👍

The only thing I hadn't expected was the way the `ISnapshotWriter` is called to `ReadSnapshot` using only `StreamId` and `Version`. In my head there would be a reference included in the `SnapshotWriterSnapshot` that is used in the `EventStore`.
But the fact that I hadn't expected is, is likely because I hadn't given it enough thought yet.

I guess it's a result of the `ISnapshotWriter.CreateSnapshot` method only returning a `bool`, rather than an object or reference.
But that does make sense as an API, given that the fallback is to let Eveneum persist a Snapshot.

All in all, I'm sure we can work with this.
It might even force us to use a more human-readable storage mechanic, which isn't a bad thing.

As for proceeding, I'm in the middle of a busy week, due to some of my colleagues unexpectedly getting sick.
If you don't mind, I'd prefer the pre-release route.
I'll try to find some time as soon as possible to play around with this change.

This feels like a great feature to me 🎉

**Comment by ThomasVandenbon** [comment]
We might be able to get around it using Blob tags...
- https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-tags?tabs=azure-ad
- https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags?tabs=azure-ad

**Comment by jkonecki** [comment]
@ThomasVandenbon 
I think tags come with extra pricing, which you might want to avoid.
I can see a few options here for implementing 'bulk delete' in `DeleteSnapshots` method:

1. Assuming your blobs will have an id in format `<streamId>-<version>` you can list blobs using a prefix `<streamId>`, parse the id to get version and delete appropriate blobs.
2. Query CosmosDB to find all snapshot documents for your stream with version lower than passed in the parameter and construct your blobId from those documents. We could add a method to Eveneum for loading all snapshots for a stream.

I wanted to avoid individual calls for deleting individual snapshots one by one as in most cases data stores offer capabilities for deleting multiple entries in one request.

**Comment by jkonecki** [comment]
Hello @ThomasVandenbon 

I've published a pre-release version of the NuGet package: 
https://www.nuget.org/packages/Eveneum/6.5.0-rc

Please try it and let me know if you need to introduce any changes. Once you confirm all is working as expected, I'll merge into main branch.

**Comment by ThomasVandenbon** [comment]
Hi @jkonecki,

We're running into an issue with the Serialization of the snapshot.
We're using a `TypeProvider` in the options of our instance of `Eveneum.EventStore`.

When the snapshot is being serialized by the `EveneumDocumentSerializer` using `SerializeSnapshot`, it's asking the `TypeProvider` for the `string`-key for the `Type` of `Eveneum.Snapshots.SnapshotWriterSnapshot`. 
However, since `Eveneum.Snapshots.SnapshotWriterSnapshot` is defined as internal, it's a bit of a hassle to provide a mapping for this type.

Could `Eveneum.Snapshots.SnapshotWriterSnapshot` be made public?

**Comment by jkonecki** [comment]
Ahh, yes - will create a new package by Monday at the latest.

Sorry about that, I thought it was covered by tests but I must have missed
this scenario.

**Comment by jkonecki** [comment]
@ThomasVandenbon a new pre-release version is out: https://www.nuget.org/packages/Eveneum/6.5.0-rc0003

You don't have to make any changes to your code, there is no need to specify custom type mappings for SnapshotWriter snapshots - you're custom type provider will not be called for them.

**Comment by jkonecki** [comment]
Hello Thomas, could you please let me know why are you using JsonSerializationBinder? There should be no need to provide type mappings through the binder *and*  ITypeProvider at the same time. On Tue, 2 May 2023, 09:26 ThomasVandenbon, ***@***.***> ***@***.***, I'm afraid we're still stuck on the same issue.Looking at the changes from the PR, it seems that the case was covered to fill in the BodyType (and MetaDataType) using a constant string.However, the JsonSerializer is still used in the JToken.FromObject ***@***.***, this.JsonSerializer)In our case, we're using a single JsonSerializer, which is also aware of the TypeProvider:var serializerSettings = new JsonSerializerSettings{  Formatting = Formatting.None,  DateParseHandling = DateParseHandling.DateTimeOffset,  TypeNameHandling = TypeNameHandling.Objects,  SerializationBinder = new JsonSerializationBinder(typeProvider)};serializerSettings.Converters.Add(new StringEnumConverter());.JsonSerializer.Create(serializerSettings)I'm guessing that because the JsonSerializer uses a JsonSerializationBinder that uses a TypeProvider, we're running into the same exception as before.I believe we've been mapping EveneumDocument in our TypeProvider for the same reason.But since Eveneum.Snapshots.SnapshotWriterSnapshot is not public, we can't do the same for that type.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ThomasVandenbon** [comment]
My understanding is as follows:
- `TypeProvider` is passed to `EventStore` to ensure that `BodyType` and `MetadataType` don't reference any namespaces or class names. Which is needed to allow for refactoring.
- `JsonSerializer` is passed to `EventStore` to give us control over how the Body is serialized. Specifically we want to include type information to ensure the correct type is referenced. But just like with the `TypeProvider`, we want to be able to refactor and therefor we use a `TypeProvider` for the `JsonSerializer` too (via a `JsonSerializationBinder`).

Is our approach incorrect?

**Comment by jkonecki** [comment]
It's not about being incorrect - I've just never ran into this kind of
approach before.

If I wanted to retain original type information then I didn't use
TypeProvider and let the library persist full type name.

Otherwise, when I use a TypeProvider, I don't need to have exact type
information.

I don't customize the serialization per type, so my JsonSerializer settings
are applied to all types.

I'll make the snapshot class public for you in a moment.

**Comment by jkonecki** [comment]
RC4 nuget package has been released.

**Comment by ThomasVandenbon** [comment]
Hi @jkonecki,

Sorry for being silent for a while. I was attending a conference and this unfortunately moved to the background.
I've just tested using `6.5.0-rc0004`.

**The good news**
`SnapshotWriterSnapshot` is indeed public and accessible, which allows us to map it to an identifier.

**The bad news**
We're being offered an unknown identifier (the identifier that was set in Eveneum).
Up until now, we have been mapping each type in our application to a format of $`{prefix}-{typeidentifier}`.
Meaning we were planning to map `SnapshotWriterSnapshot` to `Eveneum-SnapshotWriterSnapshot`.
Unfortunately, our mapper is being called with `Eveneum.SnapshotWriterSnapshot` (`.` instead of `-`), which originates from https://github.com/Eveneum/Eveneum/blob/9226cb270291b4d9e634fe93f7094bb89a1cef9e/Eveneum/Serialization/EveneumDocumentSerializer.cs#LL15C9-L15C101.

Would it be possible to not set the identifier in Eveneum and let us handle the identifier? 😅
Similar as to how we have to handle the identifier for `EveneumDocument` as well.

If not, we'll have to find a way to override this specific type to the constant you've used in Eveneum (which is a contract we'd rather avoid).

**Comment by jkonecki** [comment]
Sure, I can easily use ITypeProvider here, so you will get a call to
provide an identifier for the snapshot file. I'll try to push the new
version later on today.

**Comment by jkonecki** [comment]
@ThomasVandenbon NuGet package RC5 has been published

**Comment by ThomasVandenbon** [comment]
Hi @jkonecki the latest version works quite well.
We've managed to implement the entire flow from writing to loading snapshots (to blob storage).

We've only seen one thing that could potentially be improved.

The one case is as follows:
A snapshot has been persisted in a BLOB and for whatever reason that BLOB is removed.
When the stream is then loaded, the snapshot document in Cosmos is still found.
Meaning the stream will only be read up until the snapshot.
But when the `ISnapshotWriter.ReadSnapshot` is called we're left with 2 choices:
- Option 1: Throw an exception, meaning the stream cannot be loaded (bad)
- Option 2: Return null, which would result in a half-loaded aggregate (very bad)

It might be handy that:
If we cannot return the snapshot, that the next set of events of the stream would be read instead.
Of course this might mean that the stream is read all the way to the start, which would be bad for performance, but at least the stream would still be usable.

Maybe something to think about?
Aside from this, we're very happy with the change, thank you! 😁

**Comment by jkonecki** [comment]
Hello Thomas,

Could you please give me an example of a scenario where the blob would be
'removed'?

Is it an accidental deletion or a planned action?

The actual blob should be kept in sync with the snapshot document. If you
want to delete a snapshot manually, I suggest the document is deleted first
and the actual blob later.

**Comment by ThomasVandenbon** [comment]
@jkonecki 

The scenario we were thinking of was accidental deletion (🍺🍸🥴).

We had come to the same procedure you describe to deblock the situation, but we still wanted to let you know, as it might be something worth thinking about.  As far as we're concerned, this doesn't need to block the PR.

**Comment by jkonecki** [comment]
Ok, thanks for the clarification.

This is a very edge-case scenario and handling it properly would require
significant changes in the main logic for loading events in batches. I'll
keep it in mind when I'm refactoring this core logic.

I'm going to merge the PR soon.

**Comment by ThomasVandenbon** [comment]
@jkonecki, just to be sure.
You're not waiting for any additional input from my side, right?
I wouldn't want to be a blocker without knowing it 😅

**Comment by jkonecki** [comment]
No, Thomas - thank you very much for asking.

I had a lot of personal issues and life in general intervening - I want to
update the documentation before publishing the package.

Shouldn't be more than a couple of weeks.

Thanks again for all your help!

**Comment by ThomasVandenbon** [comment]
Ok, I hope life is treating you well, or that things will get better soon.
Best wishes to you and you're very welcome!

**Comment by MaximeJonckheere** [comment]
@jkonecki Hi, could you provide an update on this issue? Thanks.

**Comment by jkonecki** [comment]
NuGet package has been released:
https://www.nuget.org/packages/Eveneum/6.5.0

Many thanks for your help and support, @ThomasVandenbon 

@MaximeJonckheere
