### ISSUE TITLE
ReadStreamFromVersion

### ISSUE THREAD

**Issue by Aakoo76** [Eveneum/Eveneum#5]
I am evaluating on using Eveneum in my project. But I am lacking a method for reading events starting from a certain version. Could you add a method to read streams from version? 

My read model is updated from stream and for historical reasons I need to load data from events and read model. Kind of makes no sense to load all events, if I could make it by loading only missing set of events. 

Thanks!
- Ari

**Comment by jkonecki** [comment]
Hi Ari,

I want to better understand your request - how would you rebuild the
current state of the event by loading only last X events? Do you want to
load a read model as of version X from a different source and than apply
newer events (from X + 1)?

If that's the case than you might want to look into snapshots - it's
essentially what's you're doing manually. Eveneum will only load last
snapshot and newer events by default.

**Comment by Aakoo76** [comment]
Yes, I was planning to do exactly how you described. I have old database, where we have all our data. I will switch over piece by piece, by loading data first from db and then would apply events from Eveneum on top of the old data.  I will take a look at snapshots in this case.

But I could think also on conflict situations it would make sense to retrieve events that are applied after my last read. 

* Create aggregate
=>  read event stream
=> apply Events from stream
=> Set aggregate Version
* Make modifications to aggregate
* Persist events
=> conflict, because somebody else already modified the aggregate, and expected version is not matching.

Here in case of conflict, if I could have the read version stored on the aggregate, and could request new events from that version => apply the new events and try to resolve the conflict, if possible. If I didn't have the opportunity to read only latest events, I will have to read all events since last snapshot and apply only the new ones.

**Comment by jkonecki** [comment]
Your understanding of the scenario of concurrency conflict is correct.

I will work on adding the support for reading the stream from certain
version only in the next few days.

**Comment by jkonecki** [comment]
If you're on Twitter, please follow @EveneumDB. I'd like to tag you when announcing the release

**Comment by jkonecki** [comment]
The feature has been implemented in version `3.2.0`, NuGet package will be published in a moment.
