### ISSUE TITLE
Header-event transaction concerns

### ISSUE THREAD

**Issue by ThomasVandenbon** [Eveneum/Eveneum#8]
I've been going through the `EventStore` code, specifically the code in `WriteToStream`.

My understanding of the way headers and events are being saved is as follows:
The `Header`-document is inserted to check for concurrency issues and always contains the latest version. It is always created before the `Event`-documents are inserted.

What I've been wondering is:
**How does the system recover from a situation where a problem occurs after the `Header`-document has been added/updated, but before the `Event`-documents have been added?**

The only explanation I can currently think of:
- Does it just leave the `Header`-document as it is and create a gap in the stream where specific version numbers don't have corresponding `Event`-documents?
- If so, am I right in thinking that this doesn't cause issues because this kind of `Header`-document would not contain any `Event`-data?

**Comment by jkonecki** [comment]
Gaps in events is not an issue for Eveneum. There is no assumption that
actual number of event documents is the same as header version.

As much as I agree with your scenario, I haven't experienced problems like
that in over the year. CosmosDB availability is pretty good and client SDK
has built-in retries.

I plan on moving the logic fully to stored procedure in the future, so
storing events and updating the header will be executed atomically.

**Comment by ThomasVandenbon** [comment]
Okay, that clears things up for me.
Thank you for the information!
