### ISSUE TITLE
Dapr - StateClient support

### ISSUE THREAD

**Issue by perokvist** [Eveneum/Eveneum#9]
Hi,

What do you think about;
Would it be possible to remove the dependency on CosmosClient/Container, and use Dapr's StateClient, in another EventStore impl ?

/Per

**Comment by jkonecki** [comment]
I haven't looked at Dapr yet - Eveneum takes advantage of CosmosDB-specific
features (eg. Transactional batches, stored procedures), I don't know if
there are equivalent features in Dapr.

We are probably looking at keeping just the IEventStore interface and would
require a whole rewrite of the implementation.

I'll keep this issue open and report my findings after I familiarize myself
with Dapr.

**Comment by perokvist** [comment]
Great!
To my understanding dapr supports transactions for batches of the same "type".
SPs - no - what features in Eveneum uses that after batch transaction support ?
Maybe a test with just IEventStore, would answer this quickly.

thx

**Comment by jkonecki** [comment]
Stored Procedures are used for document deletion, so you don't have to pay the penalty of querying documents on the client and sending delete requests back to CosmosDB

**Comment by jkonecki** [comment]
I had a look at Dapr and here are my thoughts:

1. Dapr doesn't support Event-Sourced state natively,
1. If you want to shoe-horn events into StateClient it would be better to create an `EveneumStateClient : StateClient` that uses Eveneum, rather than the other way round. Implementing event store on top of key-value store will not be straightforward / performant,
1. If you want to implement event-sourced Dapr actors, I suggest you don't use `StateClient` at all, but inject `IEventStore` into Actor and use it directly. You would read stream inside `OnActivateAsync()` and append events / generate snapshots in individual actor methods as needed.

**Comment by perokvist** [comment]
An Eveneum state client would still tie the implementation to Cosmos through Eveneum ?
Implementing a EventStore with StateClient would cater to all Dapr state providers, even if not an optimized implementation.

The value here is keeping infrastructure out of the picture only, getting the Dapr application model.
We'll see what the future holds, but it seems that Dapr would like to play nice with Cosmos. Maybe we'll see Feed Processor and other outbox/inbox scenarios addressed.

**Comment by jkonecki** [comment]
Yes to your first question.

However, the state client api (get state by key, set state by key) is very
incompatible with event sourcing. We run into the same problem in Orleans,
and hence the whole work on LogProviders there.

Since Dapr actors are a deriverate of Orleans, the only feasible way to
support event sourcing IMHO is *not* to use state client at all.

**Comment by perokvist** [comment]
Yes, at it's current state it doesn't seem to fit the ES scenario out of the box.
It look like there might be support for other queries that might support an implementation of streams. 
Let's see how it evolves. Would be great to see a future ES(and more) on top of this app model.

https://github.com/RicardoNiepel/dapr-docs/blob/master/concepts/state-management/state-management.md#querying-state-store-directly

**Comment by yaron2** [comment]
Hi, Dapr maintainer here.

From looking into Eveneum it seems like you have some CosmosDB implementation specific needs which aren't currently covered by Dapr.

A few things to point out:

1. We are planning on supporting multi-item transactions with CosmosDB using SPs
2. We are looking into exposing SQL interfaces for the Dapr State API. This will help cater for more use cases than simple key/value.

Having Dapr be able to support more advanced needs like those described here is definitely something we want to accomplish.

We'd appreciate any kind of help to make this happen, be it feature requests or PRs.

**Comment by perokvist** [comment]
Hi,

Interesting!

1. Is this going to be "built in" or through "meta" ?
2. So the state providers that support SQL, is going to expose this (all way up to .net SDK) ?

This might open up for ES scenarios.

Using output bindings for Cosmos, is not for this scenario ?
But input binding for Cosmos Feed Processor could be useful for many scenarios like outbox patterns (of not build in the future).

**Comment by yaron2** [comment]
1. Built in. We already have a [multi item transaction API](https://github.com/dapr/docs/blob/master/reference/api/actors.md#save-actor-state---transaction), but currently it's only used for actors.
It'd be a small change for us to expose this functionality to non-actors too.

2. Yes, we'll add a new API to both HTTP and gRPc (hence client SDKS, including .NET based on our protobuf client will get it). something like `v1.0/state?query="SELECT * FROM..."`

Output bindings is more about simpler uses cases where you want to bind a piece of data into a collection with an ID.

Indee, an input binding for the Cosmos Feed Processor is very interesting and something we'd want to implement rather quickly.

**Comment by perokvist** [comment]
@yaron2 could I find these features as Issues in the .NET SDK ? (to be able to track progress)
